name: y_lints
description: Custom lint rules for enforcing architectural boundaries in a Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lints: ^4.0.0
