name: y_lints
description: Custom lint rules that enforce clean architecture boundaries (domain, data, presentation) in Dart and Flutter projects.
version: 0.0.4
repository: https://github.com/y4hoo58/y_lints
issue_tracker: https://github.com/y4hoo58/y_lints/issues

topics:
  - lint
  - architecture
  - clean-architecture
  - custom-lint
  - flutter

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lints: ^4.0.0
